### ISSUE TITLE
Overpowered Axes

### ISSUE THREAD

**Issue by flynndenby** [arthurbambou/Randomly-Adding-Anything#26]
I downloaded the mod and mid way through my play through I noticed that the swords are overwhelmingly weak. The axes however are reaching MUCH higher Attack Damage's (in the 10+ range) while the none of the swords have a damage that exceeds a diamond sword (7).

I think someone has also mentioned this but the ores that generate "end game" (in the end) are much weaker then the ones that I get just from digging the top grass layer

**Comment by flynndenby** [comment]
also every tool seems to be slower (and less powerful) then iron tools, so there's not much motivation to use anything other than the standard iron, gold, diamond ect

**Comment by thecatcore** [comment]
It‘s difficult to make balanced random.

**Comment by LeCodex** [comment]
You could use weights and a normal distribution instead of a constant one. It won't eliminate EVERY scenario, but it will dilute them a lot imo. I don't know if such thing is possible in Java, I've never used this language

**Comment by StriletsGlib** [comment]
I didn't use tools in new version, but swords seem to be buffed. Some of them have insane speed.

**Comment by deli73** [comment]
i got a material called "transanix" and it made a sword with 5 attack speed but only 2.7 damage
meanwhile a gem called "comise" made an axe that does 9 damage at 1.3 attack speed... though its durability is a bit on the low side, at around 500.

i'd propose the randomized attributes have some sort of dependent generation so that a better value of one attribute lowers the chance of a better value of another attribute. that way there'd be a lot of interesting tradeoffs!

also maybe increase the chance that you can use the items for something, cuz i got at least 2 or 3 that just made blocks and nothing else

**Comment by oliviathevampire** [comment]
This will be fixed in the 1.16 release
